// Generated by scripts/build-content.mjs. Edit files in content/ instead.
export type ContentEntry = {
  title: string;
  slug: string;
  description?: string;
  date: string;
  updated?: string;
  topic?: string;
  tags?: string[];
  pinned?: boolean;
  readingTime?: string;
  kind: "post" | "column" | "thought";
  sourcePath: string;
  content: string;
  column?: string;
  columnTitle?: string;
  order?: number;
  mediaType?: "image" | "audio" | "video" | "link" | "text";
  media?: string;
  mediaAlt?: string;
  poster?: string;
  linkTitle?: string;
  linkDescription?: string;
};

export const posts = [
  {
    "title": "注意力也是一种界面",
    "slug": "attention-is-an-interface",
    "description": "当工具越来越聪明，真正稀缺的不是功能，而是我们把注意力放在哪里。",
    "date": "2026-07-21T00:00:00.000Z",
    "updated": "2026-07-23T00:00:00.000Z",
    "topic": "产品与思考",
    "tags": [
      "产品设计",
      "注意力"
    ],
    "pinned": true,
    "readingTime": "6 分钟",
    "kind": "post",
    "sourcePath": "posts/attention-is-an-interface.md",
    "content": "工具总是在争取更短的路径：少一次点击、少一个页面、少等一秒。但如果只把效率当作终点，我们很容易做出一种**没有摩擦，也没有方向**的界面。\n\n> 好的界面不只是让事情更快发生，也应该帮助人知道什么值得发生。\n\n## 界面在分配什么\n\n每一个高亮、通知和默认选项，都在替用户分配注意力。它们看上去只是视觉决策，实际上却在参与判断。\n\n| 界面动作 | 隐含的决定 |\n| --- | --- |\n| 默认展开 | 这件事更值得先看 |\n| 红色角标 | 这件事不能等 |\n| 无限滚动 | 这里没有自然的终点 |\n\n## 摩擦不是敌人\n\n有些摩擦应该被删掉，例如重复输入和无意义的确认；另一些摩擦则应该被保留，例如发布前的停顿、删除前的复核，以及阅读长文时清晰的段落边界。\n\n```ts\ntype Friction = {\n  cost: number;\n  protectsIntent: boolean;\n};\n\nconst shouldRemove = (friction: Friction) =>\n  friction.cost > 0 && !friction.protectsIntent;\n```\n\n## 把节奏设计进去\n\n我现在更愿意先问三个问题：\n\n1. 用户来到这里时，最需要看见什么？\n2. 哪些信息可以晚一点出现？\n3. 这个流程应该在哪里自然结束？\n\n这些问题没有让界面变得更复杂，反而让许多元素失去了存在的理由。\n\n## 最后的判断\n\n注意力不是取之不尽的资源。产品真正的克制，不是少用一种颜色，而是少向用户索取一次不必要的注意。\n\n脚注也应该像在 Typora 中一样自然工作。[^attention]\n\n[^attention]: 这也是本站选择安静排版、有限强调色和明确阅读边界的原因。"
  },
  {
    "title": "我为什么重新选择本地写作",
    "slug": "local-first-writing",
    "description": "Markdown 文件、可迁移的媒体资源，以及不被平台锁住的长期写作。",
    "date": "2026-07-12T00:00:00.000Z",
    "topic": "写作系统",
    "tags": [
      "Markdown",
      "Local-first"
    ],
    "pinned": true,
    "readingTime": "5 分钟",
    "kind": "post",
    "sourcePath": "posts/local-first-writing.md",
    "content": "我仍然在 Typora 里写下第一版。不是因为它有最多的功能，而是因为一个普通的 Markdown 文件让我知道：十年后，我仍然能打开这些文字。\n\n## 文件就是作品\n\n文章不应该只存在于某个编辑器的数据库里。标题、发布日期和主题放进 YAML front matter，正文保持标准 Markdown，图片则和文章一起归档。\n\n## 发布只是一次编译\n\n写作和发布可以分离。写作阶段只关心内容；网站读取文件，生成目录、搜索索引和 RSS。\n\n- [x] 在 Typora 中完成正文\n- [x] 提交 Markdown 与媒体资源\n- [ ] 发布后继续修正\n\n## 可迁移才有长期主义\n\n真正的长期主义不是选中一个“永远不会倒闭”的平台，而是让迁移成本始终足够低。"
  },
  {
    "title": "做一个 PDF 阅读器之后，我重新理解了「位置」",
    "slug": "building-a-pdf-reader",
    "description": "阅读位置不是页码，而是一段连续体验的锚点。",
    "date": "2026-06-28T00:00:00.000Z",
    "topic": "构建手记",
    "tags": [
      "SwiftUI",
      "阅读体验"
    ],
    "pinned": false,
    "readingTime": "8 分钟",
    "kind": "post",
    "sourcePath": "posts/building-a-pdf-reader.md",
    "content": "“打开侧栏不能让正文跳一下”看起来是一条微小的要求，真正实现时却牵动了布局、缩放、滚动和状态恢复。\n\n## 页码不等于位置\n\n同一页里也有阅读进度。只记录页码，恢复后仍然可能让人失去上下文。\n\n## 变化前先保存锚点\n\n布局变化之前，保存视口中心所对应的文档坐标；布局完成以后，再把这个坐标映射回新的视口。\n\n## 两条交互路径\n\n侧栏开关是离散变化，分隔线拖拽是连续变化。它们应该共享“保持锚点”的原则，但不应该共享完全相同的更新频率。"
  },
  {
    "title": "从逐词生成理解 KV Cache",
    "slug": "understand-kv-cache",
    "description": "不从公式开始，而是从模型下一次到底重复算了什么开始。",
    "date": "2026-06-09T00:00:00.000Z",
    "topic": "AI 学习",
    "tags": [
      "Transformer",
      "推理"
    ],
    "pinned": false,
    "readingTime": "9 分钟",
    "kind": "post",
    "sourcePath": "posts/understand-kv-cache.md",
    "content": "理解 KV Cache 最直观的方式，是先看自回归生成里那些被重复计算的部分。\n\n## Prefill 与 Decode\n\nPrefill 一次处理完整提示词，Decode 则每次只生成一个新 token。\n\n```mermaid\nflowchart LR\n  A[Prompt] --> B[Prefill]\n  B --> C[KV Cache]\n  C --> D[Decode one token]\n  D --> C\n```\n\n## 缓存的是什么\n\n过去 token 对应的 Key 和 Value 不会因为新 token 到来而变化，所以可以保存下来，只计算新位置的投影。\n\n## 空间换时间\n\n缓存减少计算，却增加显存占用。批量、序列长度与层数共同决定了这笔开销。\n\n$$\n\\text{KV memory} \\propto 2 \\times L \\times H \\times T\n$$"
  }
] as ContentEntry[];
export const columns = [
  {
    "title": "01 · 从最小闭环开始",
    "slug": "smallest-closed-loop",
    "description": "先让最重要的一条路径真正跑通。",
    "date": "2026-07-04T00:00:00.000Z",
    "topic": "独立开发",
    "tags": [
      "产品",
      "工程"
    ],
    "column": "building-in-public",
    "columnTitle": "一个人造产品",
    "order": 1,
    "readingTime": "7 分钟",
    "kind": "column",
    "sourcePath": "columns/building-in-public/01-smallest-loop.md",
    "content": "一个人的时间有限，所以“完整”必须被重新定义。对我来说，完整不是一次做完所有功能，而是先让最重要的一条路径首尾相接。\n\n## 什么是最小闭环\n\n它必须包含触发、完成和反馈。只有按钮不算闭环，只有数据结构也不算。\n\n## 把想法切成动作\n\n以一个文件浏览器为例，第一步不是标签、搜索或批量操作，而是：\n\n1. 创建文件夹；\n2. 创建 Markdown 文件；\n3. 刷新列表；\n4. 自动选中新项目。\n\n## 可观察的完成\n\n闭环需要能被人看见，也能被测试验证。每次完成之后，都应该留下足够明确的证据。\n\n## 下一步\n\n当闭环成立，再进入命名、删除和上下文菜单。功能扩展不再是猜测，而是沿着已经成立的路径自然生长。"
  },
  {
    "title": "02 · 让状态变得可靠",
    "slug": "stable-state",
    "description": "状态设计的关键，是明确谁拥有事实。",
    "date": "2026-07-10T00:00:00.000Z",
    "topic": "独立开发",
    "tags": [
      "状态管理"
    ],
    "column": "building-in-public",
    "columnTitle": "一个人造产品",
    "order": 2,
    "readingTime": "6 分钟",
    "kind": "column",
    "sourcePath": "columns/building-in-public/02-stable-state.md",
    "content": "状态问题很少只是“少刷新了一次”。更常见的原因是多个地方都以为自己拥有最终事实。\n\n## 唯一事实来源\n\n先确定数据由谁拥有，再决定界面如何派生。临时交互状态可以留在视图，持久事实必须有明确边界。\n\n## 乐观更新\n\n乐观更新让操作显得即时，但失败时必须能够回滚，并且不能让选择状态丢失。\n\n## 可恢复\n\n真正可靠的状态不是永不失败，而是在失败以后仍然知道应该回到哪里。"
  },
  {
    "title": "03 · 带着证据发布",
    "slug": "ship-with-evidence",
    "description": "“我改完了”不是完成，“用户可以确认它好了”才是。",
    "date": "2026-07-18T00:00:00.000Z",
    "topic": "独立开发",
    "tags": [
      "验证",
      "发布"
    ],
    "column": "building-in-public",
    "columnTitle": "一个人造产品",
    "order": 3,
    "readingTime": "5 分钟",
    "kind": "column",
    "sourcePath": "columns/building-in-public/03-ship-with-evidence.md",
    "content": "发布前最重要的工作不是再写一段漂亮总结，而是找到足以支持结论的证据。\n\n## 验证真实路径\n\n测试最小单元很重要，但用户真正经历的是一条完整路径。至少有一次验证应该从入口走到结果。\n\n## 不隐藏边界\n\n没有验证的部分要明确说出来。诚实的边界比虚假的完整更有价值。\n\n## 留下下一步\n\n一次发布应该让下一次开发更容易开始，而不是重新理解所有上下文。"
  }
] as ContentEntry[];
export const thoughts = [
  {
    "title": "雨后的城市",
    "slug": "rainy-night",
    "date": "2026-07-24T14:36:00.000Z",
    "tags": [
      "摄影"
    ],
    "mediaType": "image",
    "media": "https://images.unsplash.com/photo-1537351685860-1e89e9ecb843?auto=format&fit=crop&w=1400&q=84",
    "mediaAlt": "雨后城市街道与灯光倒影",
    "kind": "thought",
    "sourcePath": "thoughts/rainy-night.md",
    "content": "下过雨的路面会把城市复制一遍。上面那个版本负责赶路，下面那个版本只负责发光。"
  },
  {
    "title": "今天的声音",
    "slug": "field-recording",
    "date": "2026-07-22T10:10:00.000Z",
    "tags": [
      "声音"
    ],
    "mediaType": "audio",
    "media": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    "kind": "thought",
    "sourcePath": "thoughts/field-recording.md",
    "content": "写代码时循环播放的一段声音。相比歌单，我最近更喜欢没有明确歌词的背景，它不会替思考决定方向。"
  },
  {
    "title": "慢一点看",
    "slug": "slow-motion",
    "date": "2026-07-19T01:20:00.000Z",
    "tags": [
      "影像"
    ],
    "mediaType": "video",
    "media": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "poster": "https://images.unsplash.com/photo-1544655205-dcbeb868c648?auto=format&fit=crop&w=1400&q=82",
    "kind": "thought",
    "sourcePath": "thoughts/slow-motion.md",
    "content": "很多细节不是不存在，只是平常的速度太快了。"
  },
  {
    "title": "链接不是收藏，是路径",
    "slug": "links-are-paths",
    "date": "2026-07-16T04:05:00.000Z",
    "tags": [
      "阅读"
    ],
    "mediaType": "link",
    "media": "https://indieweb.org/Webmention",
    "linkTitle": "Webmention · IndieWeb",
    "linkDescription": "让不同网站之间的回复、喜欢与引用重新连接起来。",
    "kind": "thought",
    "sourcePath": "thoughts/links-are-paths.md",
    "content": "想把最近读到的好东西放回来。收藏夹很容易变成仓库，链接出现在上下文里，才重新变成一条路。"
  }
] as ContentEntry[];
