import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const root = process.cwd();
const contentRoot = path.join(root, "content");
const output = path.join(root, "app", "lib", "generated-content.ts");

function readMarkdownTree(directory, kind) {
  if (!fs.existsSync(directory)) return [];

  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return readMarkdownTree(fullPath, kind);
    if (!entry.name.endsWith(".md")) return [];

    const raw = fs.readFileSync(fullPath, "utf8");
    const parsed = matter(raw);
    const relative = path.relative(contentRoot, fullPath);
    const slug = parsed.data.slug ?? path.basename(entry.name, ".md");
    return [
      {
        ...parsed.data,
        slug,
        kind,
        sourcePath: relative,
        content: parsed.content.trim(),
      },
    ];
  });
}

const posts = readMarkdownTree(path.join(contentRoot, "posts"), "post").sort(
  (a, b) => Date.parse(b.date) - Date.parse(a.date),
);
const columns = readMarkdownTree(path.join(contentRoot, "columns"), "column").sort(
  (a, b) => (a.order ?? 999) - (b.order ?? 999),
);
const thoughts = readMarkdownTree(path.join(contentRoot, "thoughts"), "thought").sort(
  (a, b) => Date.parse(b.date) - Date.parse(a.date),
);

const source = `// Generated by scripts/build-content.mjs. Edit files in content/ instead.
export type ContentEntry = {
  title: string;
  slug: string;
  description?: string;
  date: string;
  updated?: string;
  topic?: string;
  tags?: string[];
  pinned?: boolean;
  readingTime?: string;
  kind: "post" | "column" | "thought";
  sourcePath: string;
  content: string;
  column?: string;
  columnTitle?: string;
  order?: number;
  mediaType?: "image" | "audio" | "video" | "link" | "text";
  media?: string;
  mediaAlt?: string;
  poster?: string;
  linkTitle?: string;
  linkDescription?: string;
};

export const posts = ${JSON.stringify(posts, null, 2)} as ContentEntry[];
export const columns = ${JSON.stringify(columns, null, 2)} as ContentEntry[];
export const thoughts = ${JSON.stringify(thoughts, null, 2)} as ContentEntry[];
`;

fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, source);
console.log(
  `Synced ${posts.length} posts, ${columns.length} column entries, and ${thoughts.length} thoughts.`,
);
